### ISSUE TITLE
Bad prefix on rx side

### ISSUE THREAD

**Issue by ognlvnt** [deptofdefense/gr-uaslink#7]

**Comment by flynn378** [comment]
This is normally because you do not have enough or too much gain /Antenna issues.  The too much comes from saturation issues.  You will probably see some of these messages even if you get the data through.  This means that enough energy was present for the burst detector to trigger, but not enough to actually get good data out of the full demod, or it triggered at the wrong time.  This code was designed to be the simplest possible code that worked.  It is not an example of a fully functional error free code design.  It was provided as a starting point for a hack-fest.

**Comment by ognlvnt** [comment]
I am aware of that. How was the latency of control messages on the rx side? Control signal goes approximately 1 minute to rpi and I checked Tim O'Sheas' burst article and cant find a way to minimize latency. Does it really depend on hardware?

**Comment by flynn378** [comment]
The latency was low enough to fly a UAS inside of a building.  The messages are very short, although the receiving PI did need to have CPU freq turned up for better control.  It is possible to control it with the lowest cpu speed.  THE frequency, antenna, and gain settings did need to be matched.   For 1 Minute messages I would guess you either need more power or less power (make a capture on the RPI and see what the power levels are.  Also move the frequency into a "quiet" frequency zone without a lot of bursts or energy fro where you are.  If you have WiFi, Zigbee, etc on a 2.4 channel near the system that will raise the processing requirements in those frequencies.

**Comment by ognlvnt** [comment]
we tested on 433mhz distance between tx and rx antennas was 50cm I guess its lack of power. By the way we didnt use open embedded on rpi3 its running on rasbian os. Is there a chance resulting in latency?

**Comment by flynn378** [comment]
I am not sure how it runs on rasbian.  At the time of development rasbian did not support the 64bit processor as 64bit, it was compiled for 32bits.  The OE image was built to support 64bit.  433Mhz can also have a lot of bursting signals.  If you see detection information being printed from the burst framer without transmitting you are getting other bursts.  Any lack of processing by the RPI will be mad worse by this situation and increase latency.  An Odroid Xu4 is a better embedded computer option, it has USB 3.0, can use EMMC cards, and runs very fast in 64bit mode.  The RPi was selected because they are easy to acquire and there was more information and sensors which could be purchased locally.

**Comment by ognlvnt** [comment]
thank you very much
